/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddressSchema extends BaseModel {
  static $columns = [
    'addressableId',
    'addressableType',
    'cityId',
    'complement',
    'countryId',
    'createdAt',
    'deletedAt',
    'id',
    'latitude',
    'longitude',
    'neighborhood',
    'number',
    'postalCode',
    'stateId',
    'street',
    'updatedAt',
  ] as const
  $columns = AddressSchema.$columns
  @column()
  declare addressableId: number
  @column()
  declare addressableType: string
  @column()
  declare cityId: number | null
  @column()
  declare complement: string | null
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare neighborhood: string
  @column()
  declare number: string
  @column()
  declare postalCode: string
  @column()
  declare stateId: number | null
  @column()
  declare street: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChurchSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = ChurchSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CitySchema extends BaseModel {
  static $columns = ['createdAt', 'ibgeCode', 'id', 'name', 'stateId', 'updatedAt'] as const
  $columns = CitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare ibgeCode: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare stateId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CountrySchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = CountrySchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MinistryRoleUserSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ministryRoleId', 'updatedAt', 'userId'] as const
  $columns = MinistryRoleUserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ministryRoleId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class MinistryRoleSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = MinistryRoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'description', 'id', 'module', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare module: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PriestSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'phone', 'updatedAt'] as const
  $columns = PriestSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfilePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'permissionId', 'profileId', 'updatedAt'] as const
  $columns = ProfilePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare permissionId: number
  @column({ isPrimary: true })
  declare profileId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = ProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SacramentTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = SacramentTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SacramentSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'id',
    'receivedChurch',
    'receivedCityId',
    'receivedCountryId',
    'receivedDate',
    'receivedStateId',
    'sacramentTypeId',
    'updatedAt',
    'userId',
  ] as const
  $columns = SacramentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare receivedChurch: string
  @column()
  declare receivedCityId: number
  @column()
  declare receivedCountryId: number
  @column.date()
  declare receivedDate: DateTime
  @column()
  declare receivedStateId: number
  @column()
  declare sacramentTypeId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class StateSchema extends BaseModel {
  static $columns = [
    'countryId',
    'createdAt',
    'deletedAt',
    'ibgeCode',
    'id',
    'name',
    'uf',
    'updatedAt',
  ] as const
  $columns = StateSchema.$columns
  @column()
  declare countryId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare ibgeCode: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare uf: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'id', 'name', 'updatedAt'] as const
  $columns = UserTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = [
    'birthCityId',
    'birthCountryId',
    'birthDate',
    'birthStateId',
    'communityId',
    'createdAt',
    'deletedAt',
    'email',
    'fullName',
    'id',
    'includeInScale',
    'password',
    'phone',
    'profileId',
    'responsible1Name',
    'responsible1Phone',
    'responsible2Name',
    'responsible2Phone',
    'updatedAt',
    'userTypeId',
  ] as const
  $columns = UserSchema.$columns
  @column()
  declare birthCityId: number | null
  @column()
  declare birthCountryId: number | null
  @column.date()
  declare birthDate: DateTime | null
  @column()
  declare birthStateId: number | null
  @column()
  declare communityId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare includeInScale: boolean
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare profileId: number | null
  @column()
  declare responsible1Name: string | null
  @column()
  declare responsible1Phone: string | null
  @column()
  declare responsible2Name: string | null
  @column()
  declare responsible2Phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userTypeId: number | null
}

export class VerifyConnectionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'updatedAt'] as const
  $columns = VerifyConnectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
